CREATE TABLE IF NOT EXISTS NW_MESSAGE (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_USER bigint DEFAULT NULL,
    SENDER varchar(30) NOT NULL,
    TEMPLATE varchar(40) NOT NULL,
    CONTENT json DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_USER) REFERENCES NW_USER(ID)
);