CREATE TABLE IF NOT EXISTS NW_MESSAGE_TRACE (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_MESSAGE bigint NOT NULL,
    TYPE varchar(20) NOT NULL,
    TO varchar(256) NOT NULL,
    STATUS varchar(30) DEFAULT NULL,
    DETAIL varchar(1000) DEFAULT NULL,
    ATTEMPT int NOT NULL DEFAULT 1,
    SCHEDULED timestamp DEFAULT NULL,
    SENT timestamp DEFAULT NULL,
    IDENTIFIER varchar(200) DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_MESSAGE) REFERENCES NW_MESSAGE(ID),
    UNIQUE KEY `MESSAGE_MAIL` (`ID_MESSAGE`, `TO`, `ATTEMPT`)
);