CREATE TABLE IF NOT EXISTS NW_CREATOR_PERSONAL_CUSTOMER_NOTE (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_CREATOR bigint NOT NULL,
	ID_CUSTOMER bigint NOT NULL,
	TEXT varchar(1000) NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_CREATOR) REFERENCES NW_CREATOR(ID),
	FOREIGN KEY(ID_CUSTOMER) REFERENCES NW_CUSTOMER(ID),
	UNIQUE KEY `CREATOR_PERSONAL_CUSTOMER_NOTE` (`ID_CREATOR`,`ID_CUSTOMER`)
);