CREATE TABLE IF NOT EXISTS NW_INFORMATION_SHARING_POLICY (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME bit DEFAULT 0,
    LAST_NAME bit DEFAULT 0,
    BIRTH_DATE bit DEFAULT 0,
    EMAIL_ADDRESS bit DEFAULT 0,
    PHONE_NUMBER bit DEFAULT 0,
    PARTIAL_ADDRESS bit DEFAULT 0,
    FULL_ADDRESS bit DEFAULT 0,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp
);