CREATE TABLE IF NOT EXISTS NW_CREATOR_SPECIFIC_ISP (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_ISP bigint UNIQUE KEY NOT NULL,
	ID_CREATOR bigint NOT NULL,
	ID_CUSTOMER bigint NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_ISP) REFERENCES NW_INFORMATION_SHARING_POLICY(ID),
	FOREIGN KEY(ID_CREATOR) REFERENCES NW_CREATOR(ID),
	FOREIGN KEY(ID_CUSTOMER) REFERENCES NW_CUSTOMER(ID),
	UNIQUE KEY `CREATOR_CUSTOM_ISP` (`ID_CREATOR`,`ID_CUSTOMER`)
);