CREATE TABLE IF NOT EXISTS NW_CREATOR_COMMISSION_TEMPLATE (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_CREATOR bigint NOT NULL,
    TITLE varchar(200) NOT NULL,
    DESCRIPTION varchar(500) DEFAULT NULL,
    ICON varchar(20) DEFAULT NULL,
    ICON_COLOR varchar(20) DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_CREATOR) REFERENCES NW_CREATOR(ID),
	UNIQUE KEY `CREATOR_COMMISSION_TEMPLATE` (`ID_CREATOR`, `TITLE`)
);