CREATE TABLE IF NOT EXISTS NW_COMMISSION_ANNOTATION (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_COMMISSION bigint NOT NULL,
    TEXT text NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_COMMISSION) REFERENCES NW_COMMISSION(ID)
);