CREATE TABLE IF NOT EXISTS NW_COMMISSION_RESOURCE (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_COMMISSION bigint NOT NULL,
    NAME varchar(200) NOT NULL,
    LINK varchar(5000) NOT NULL,
    DIRECTION varchar(20) NOT NULL,
    PRIVATE bit NOT NULL DEFAULT 0,
    REFERENCE bit NOT NULL DEFAULT 0,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_COMMISSION) REFERENCES NW_COMMISSION(ID)
);