CREATE TABLE IF NOT EXISTS NW_COMMISSION_ORDER (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_COMMISSION bigint NOT NULL,
    DEADLINE date DEFAULT NULL,
    PAYMENT varchar(10) DEFAULT NULL,
    PAYMENT_ADVANCE varchar(10) DEFAULT NULL,
    DIRECTION varchar(20) NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_COMMISSION) REFERENCES NW_COMMISSION(ID)
);