export enum Direction {
    
    CREATOR_TO_CREATOR = 'CREATOR-TO-CREATOR',
    CREATOR_TO_CUSTOMER = 'CREATOR-TO-CUSTOMER',
    CUSTOMER_TO_CUSTOMER = 'CUSTOMER-TO-CUSTOMER',
    CUSTOMER_TO_CREATOR = 'CUSTOMER-TO-CREATOR'
}