CREATE TABLE IF NOT EXISTS NW_CUSTOMER (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_USER bigint UNIQUE KEY DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp ,
	FOREIGN KEY(ID_USER) REFERENCES NW_USER(ID)
);