CREATE TABLE IF NOT EXISTS NW_CREATOR_DEFAULT_ISP (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_ISP bigint UNIQUE KEY NOT NULL,
	ID_CREATOR bigint UNIQUE KEY NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_ISP) REFERENCES NW_INFORMATION_SHARING_POLICY(ID),
	FOREIGN KEY(ID_CREATOR) REFERENCES NW_CREATOR(ID)
);