CREATE TABLE IF NOT EXISTS NW_COMMISSION_ACTION (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_COMMISSION bigint NOT NULL,
    TYPE varchar(20) NOT NULL,
    STATUS varchar(30) DEFAULT NULL,
    DESCRIPTION varchar(300) DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_COMMISSION) REFERENCES NW_COMMISSION(ID)
);